services:

  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "55681:55681" # OTLP HTTP

  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"

  postgres:
    image: postgres
    volumes:
      - ./BaseContagemPostgreSql.sql:/docker-entrypoint-initdb.d/1-basecontagem.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2025!"
    ports:
      - "5432:5432"

  mysql:
    image: mysql:9.0
    volumes:
      - ./BaseContagemMySql.sql:/docker-entrypoint-initdb.d/1-basecontagem.sql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2025!"
      MYSQL_DATABASE: "basecontagem"
    ports:
      - "3306:3306"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-CTP2.1-ubuntu-22.04
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2025!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./BaseContagemSqlServer.sql:/init/BaseContagemSqlServer.sql
    command: >
      /bin/bash -c "
        echo 'Inicializando SQL Server...' &&
        /opt/mssql/bin/sqlservr & 
        sleep 20 && 
        echo 'Executando criacao da base de testes...' &&
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SqlServer2025!' -C -i /init/BaseContagemSqlServer.sql
         wait
      "